{"name": "test_reg_duplicate_name", "status": "failed", "statusDetails": {"message": "AssertionError: assert 409 == 304\n  -409\n  +304", "trace": "self = <test_api.TestAPI object at 0x7fbe6418e550>\napi = <api_client.ApiClient object at 0x7fbe64285880>\n\n    @pytest.mark.API\n    def test_reg_duplicate_name(self, api):\n        \"\"\"\n        CHECK DUPLICATE USERNAMES\n    \n        Step 1:\n        Add user to db\n        Step 2:\n        Try to add user with same name via register page\n    \n        EXPECT: status_code == 304\n        \"\"\"\n        self.builder.add_user(api.get_user())\n        resp = api.reg_user(api.get_user().username, \"E47gN@er.ty\", \"3\", \"3\" )\n        self.builder.del_user(api.get_user())\n>       assert resp.status_code == 304\nE       assert 409 == 304\nE         -409\nE         +304\n\ntest_api.py:145: AssertionError"}, "description": "\n        CHECK DUPLICATE USERNAMES \n        \n        Step 1:\n        Add user to db\n        Step 2:\n        Try to add user with same name via register page\n        \n        EXPECT: status_code == 304\n        ", "start": 1590595621409, "stop": 1590595622128, "uuid": "e7246bb5-5a2e-440b-aab0-ce4ff57d2eaf", "historyId": "94a0359f6a01dc0d8641f66997215466", "testCaseId": "de981cb167907d08c124c65dc4145643", "fullName": "test_api.TestAPI#test_reg_duplicate_name", "labels": [{"name": "tag", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "host", "value": "alex-Z87X-UD3H"}, {"name": "thread", "value": "3006-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}